### ISSUE TITLE
Define job object properties

### ISSUE THREAD

**Issue by Meysam-Arshadi** [OlushoreOdude/nyf-job-board#1]
What key-value we expect a job have and base on that we can start front-end and back-end design

**Comment by SanaAsaf** [comment]
{
  "job_id": "12345",
  "job_title": "Software Engineer",
  "company": "Acme Corporation",
  "location": "New York, NY",
  "Work Arrangement":"Remote"
  "description": "We are seeking a skilled Software Engineer to join our dynamic team...",
  "requirements": [
    "Bachelor's degree in Computer Science or related field",
    "Proficiency in programming languages such as Java, Python, or C++",
    "Experience with web development frameworks (e.g., React, Angular)",
    "Strong problem-solving and communication skills"
  ],
  "posted_date": "2023-07-24",
  "deadline": "2023-08-30",
  "salary": "$90,000 - $110,000 per year",
  "contact": {
    "name": "John Smith",
    "email": "john.smith@example.com",
    "phone": "(555) 123-4567"
  }
}


Work Arrangement : Remote,Hybrid,Inperson
