### ISSUE TITLE
Transform the data fetched from Arbeit API

### ISSUE THREAD

**Issue by Meysam-Arshadi** [OlushoreOdude/nyf-job-board#10]
We need a function that takes the data that we received from a third party and transforms it (changes it) into the shape and structure that we use for NYF.

Most likely, the data we get back from 3rd parties will contain lots of fields that we don't need so we need a way to normalise and simplify jobs data.

This function should exist in it's own file, e.g. `transformData.js`

The input to the function is the data from the 3rd party api.
The return from the function is the type of data that NYF uses

**Comment by kahei-li** [comment]
@ali1373107 remember to review this with the team to swap things around maybe if you unable to work on this ticket for a couple of days :).

**Comment by Meysam-Arshadi** [comment]
Hi @OlushoreOdude and @SanaAsaf. Should we assign this ticket to you guys as me and @ali are working on front-end at the moment?

**Comment by OlushoreOdude** [comment]
@Meysam-Arshadi @ali1373107 reassigned and closed with pull request #153
