### ISSUE TITLE
🐛 Fixing bugs at SelectedJob.jsx

### ISSUE THREAD

**Issue by Meysam-Arshadi** [OlushoreOdude/nyf-job-board#107]
Issued this ticket based on Oliver's comment on ticket #81 (closed now):

`selectedJob = jobs[0];` at `SelectedJob.jsx` component is mutating props, which is _possible_ and will work here, but it is strongly recommended that you don't do this with React because it can cause bugs and problems later on if you started to add more features to this component.

https://legacy.reactjs.org/docs/components-and-props.html#props-are-read-only

You can read up on it but basically, if you have a value that might change inside the component, then this value should be held as local state. You could use `useState` to do this but in this case the value will not change after the first render so you can [simply create a new variable](https://react.dev/learn/keeping-components-pure#local-mutation-your-components-little-secret), like

```
	let jobToDisplay = selectedJob;
	if (!jobToDisplay && jobs.length > 0) {
		// Display details of the first job if no job is selected
		jobToDisplay = jobs[0];
	}
```

**Comment by samhoooo** [comment]
As a little hint, I think you can pass `setSelectedJob` as prop to `SelectedJob` component to achieve it:

```
<SelectedJob selectedJob={selectedJob} setSelectedJob={setSelectedJob} jobs={jobsData} />
```

**Comment by Meysam-Arshadi** [comment]
Initialised local state for the job to display at `SelectedJob.jsx` using the `useState` hook.

```
	const [jobToDisplay, setJobToDisplay] = useState(selectedJob);

	// Display details of the first job if no job is selected
	if (!jobToDisplay && jobs.length > 0) {
		setJobToDisplay(jobs[0]);
	}
```
