### ISSUE TITLE
readme for branches and pull request best practise

### ISSUE THREAD

**Issue by OlushoreOdude** [OlushoreOdude/nyf-job-board#22]

**Comment by kahei-li** [comment]
@OlushoreOdude what's the update with this ticket? Is this one done now?
Also is the output shared and its clear to everyone on the team to follow through?

**Comment by OlushoreOdude** [comment]
@kahei-li , I think this was linked to a team decision, i'll review if it is still needed and update or close ticket .

**Comment by OlushoreOdude** [comment]
issue cancelled and closed
