### ISSUE TITLE
Set up the Postgress

### ISSUE THREAD

**Issue by Meysam-Arshadi** [OlushoreOdude/nyf-job-board#6]
Look into pg admin

**Comment by SanaAsaf** [comment]
[nyf_job_board.ERDiagram (1).pdf](https://github.com/OlushoreOdude/nyf-job-board/files/12266970/nyf_job_board.ERDiagram.1.pdf)

**Comment by OlushoreOdude** [comment]
## estimated time to complete - TBC needs review in 24 hrs

looked into pgAdmin, @SanaAsaf and i are set up, will add more info as we progress, may split the ticket to incorporate testing and define the next stage but will review after update.

**Comment by OlushoreOdude** [comment]
closed with pull request #153
