### ISSUE TITLE
Display Search.jsx job results from external API (Rapid API) in Home.js

### ISSUE THREAD

**Issue by Meysam-Arshadi** [OlushoreOdude/nyf-job-board#63]

**Comment by kahei-li** [comment]
@ali1373107  have a think about this task if we are going to grab directly from Postgres now instead of from external rapidAPI

**Comment by kahei-li** [comment]
Also don't forget to add some more details to this task. And maybe a breakdown of steps for others when they read this task they know what this involves and progress %.
