### ISSUE TITLE
Rapid API is blocked due to amount of calls - api.js and Home.js needs to be modified

### ISSUE THREAD

**Issue by Meysam-Arshadi** [OlushoreOdude/nyf-job-board#68]
The Rapid API is blocked and api.js and Home.js need to be modified to read the data from data.json for now or @SanaAsaf we can use Arbeitnow?

**Comment by SanaAsaf** [comment]
Worked with @Meysam-Arshadi and changed to free API Arbeitnow.
Updated 3 files.
Home.js
