### ISSUE TITLE
Create a fetchArbeitnowData Component

### ISSUE THREAD

**Issue by oliverlloyd** [OlushoreOdude/nyf-job-board#77]

**Comment by kahei-li** [comment]
@OlushoreOdude @SanaAsaf would this be of you working on this for sprint-3 right?
Make sure to have ownership assigned for each ticket

**Comment by kahei-li** [comment]
Hi @SanaAsaf, what's the progress with this ticket?

**Comment by SanaAsaf** [comment]
The fetchArbeitnowData component uses the axios library to make a GET request to the "https://www.arbeitnow.com/api/job-board-api" endpoint. It retrieves data from the external API and returns the response data. If any error occurs during the request, the function logs the error and throws an exception with a descriptive error message.
