### ISSUE TITLE
Create a `SelectedJob` component. When I select a job it appears in SelectedJob

### ISSUE THREAD

**Issue by oliverlloyd** [OlushoreOdude/nyf-job-board#79]
This component is a pure component that takes the props

- `title`
- `location`
- `description`
- `?`
- `etc`

See: https://react.dev/reference/react/PureComponent

When a job is clicked upon in the Home page the details for this job should show in the right hand pane of the page

**Comment by Meysam-Arshadi** [comment]
- [ ] `SelectedJob.jsx` component created.
- [ ] `JobCard.jsx` and `JobcardContainer.jsx`, and `Home.js` modified to display the selected job.
- [ ] If you click on a job card, the selected job will be displayed on the 3rd column.
- [ ] If no job is selected, the first job card detail will display on the 3rd column.
