### ISSUE TITLE
Create a JobNotSelected component

### ISSUE THREAD

**Issue by oliverlloyd** [OlushoreOdude/nyf-job-board#81]
This component should appear when there is no selected job on the Home page. It should show a message a bit like "No job is selected"

**Comment by kahei-li** [comment]
@Meysam-Arshadi @ali1373107  would this be one of you working on this for sprint-3 right?
Make sure to have ownership assigned for each ticket :)

**Comment by Meysam-Arshadi** [comment]
Thanks @kahei-li. Sure. I have assigned it to myself and will get it done by the end of 2nd sprint. :)

**Comment by Meysam-Arshadi** [comment]
Hi @oliverlloyd. :)

Do we still need this component, considering that currently `if (!selectedJob && jobs.length > 0)` at `SelectedJob.jsx` component, it will show the 1st job on the JobCardContainer and we always have a selected job displayed on 3rd column.

**Comment by Meysam-Arshadi** [comment]
Thanks for your detailed review @oliverlloyd and the tips on `selectedJob = jobs[0]` I will issue a ticket for it and will make the changes accordingly.

**Comment by kahei-li** [comment]
@Meysam-Arshadi well done mate. I like that you are doing all the details and interactions on this ticket. Me jumping on here and can see the progress and next steps right away is very helpful!

**Comment by kahei-li** [comment]
@Meysam-Arshadi Now about this ticket then. Since we don't need this component - can we mark this as done or cancelled?
Unless you have more to do on this?

**Comment by Meysam-Arshadi** [comment]
Thanks @kahei-li ! :)
I just need to issue a ticket for the required changes mentioned above, and will cancel this ticket
