### ISSUE TITLE
Create a Show recent jobs only checkbox and Search.css

### ISSUE THREAD

**Issue by oliverlloyd** [OlushoreOdude/nyf-job-board#82]
At the bottom of the left hand panel on the Home page there should be a checkbox with a label "Only show recent jobs"

There should be a piece of state `const [showRecent, setShowRecent] = useState...` that holds the checked or not checked state of this checkbox

Reasearch:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input/checkbox
https://duckduckgo.com/?q=react+state+checkbox&ia=web

**Comment by kahei-li** [comment]
@Meysam-Arshadi @ali1373107 This could be a stretch goal for this sprint-3? Make sure to have ownership assigned for each ticket :)
If not done, can always reassign to others to complete next sprint.

**Comment by Meysam-Arshadi** [comment]
Thanks @kahei-li and sorry I have missed your comment. I am working on this ticket today.

**Comment by Meysam-Arshadi** [comment]
- [x] Checkbox and `useState` added to the `Search.jsx` component.
- [x] `const filteredJobsByDate` should be modified to filter jobs by date once we have our DB running. At the moment Arbeitnow API does not offer date key-value as far as I could find.

**Note for @ali1373107**: Please read above comments when modifying this component.

**Comment by Meysam-Arshadi** [comment]
If a job is still active and available, user must be able to see and apply for the job. So the group decided not to have a Show recent jobs only checkbox.
