### ISSUE TITLE
Create a `refresh()` function on the backend

### ISSUE THREAD

**Issue by oliverlloyd** [OlushoreOdude/nyf-job-board#85]
We need a way to manually refresh the data.

Create a `refresh()` function that calls 

- fetchJobData()
- transformData()
- insertData()

Consider that each of these functions will return their results (const fetched = fetchJobData()). You will then need to pass in that data in `transformData(fetchedData)`

Also consider what happens if a fetch call fails. Consider a try catch

Research
https://duckduckgo.com/?q=async+await&ia=web
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise

**Comment by OlushoreOdude** [comment]
estimated time to complete 14 hrs

**Comment by OlushoreOdude** [comment]
will open a pull request for each inner function to simplify code review

**Comment by oliverlloyd** [comment]
> will open a pull request for each inner function to simplify code review

There are tickets for each of the inner functions in the board.

https://github.com/OlushoreOdude/nyf-job-board/issues/77 for fetching the data - should be a promise (async)
https://github.com/OlushoreOdude/nyf-job-board/issues/10 for transforming the fetched data - (does not need to be a promise (sync)
and
https://github.com/OlushoreOdude/nyf-job-board/issues/11 for inserting the transformed data into the api - I'm not sure if this is an async call or not, depends on how you insert the data.

You can do each of these tickets by itself and then the work for the refresh function is to bring each of these functions together so that when you call `refresh()` is executes each of the separate tasks in order.

I'm raising this here as I notice  @ali1373107 is already assigned to https://github.com/OlushoreOdude/nyf-job-board/issues/10

**Comment by OlushoreOdude** [comment]
thanks @oliverlloyd, will do as suggested. i think i have combined the insert and transform in one branch but will split into two when the functions are updated.
