### ISSUE TITLE
DB Schema

### ISSUE THREAD

**Issue by SanaAsaf** [OlushoreOdude/nyf-job-board#88]
CREATE TABLE job (
    job_id SERIAL PRIMARY KEY,
    job_title TEXT NOT NULL,
    company TEXT NOT NULL,
    hired_from_cyf BOOLEAN NOT NULL,
    location TEXT NOT NULL,
    work_arrangement TEXT NOT NULL,
    work_experience TEXT NOT NULL,
    description TEXT NOT NULL,
    deadline_date DATE, 
    url TEXT,
    salary INT 
);

**Comment by SanaAsaf** [comment]
![Image](https://github.com/OlushoreOdude/nyf-job-board/assets/85436780/e2573fd3-c178-49be-b0ca-6b452db9225c)

**Comment by SanaAsaf** [comment]
INSERT INTO jobs (
    job_title,
    company,
    hired_from_cyf,
    location,
    work_arrangement,
    work_experience,
    description,
    deadline_date,
    url,
    salary
)
VALUES
    (
        'Software Engineer',
        'Acme Corporation',
        true,
        'New York, NY',
        'Remote',
        'Entry Level',
        'We are seeking a skilled Software Engineer to join our dynamic team...',
        '2023-08-15',
        'https://example.com/job-posting',
        75000
    ),
    (
        'Data Analyst',
        'Tech Solutions Inc.',
        false,
        'San Francisco, CA',
        'In-Person',
        'Mid-Level',
        'Join our data team and analyze complex datasets to drive business insights...',
        '2023-08-30',
        'https://example.com/data-analyst-job',
        60000
    ),
    (
        'Product Manager',
        'InnovateTech',
        true,
        'Remote',
        'Remote',
        'Senior Level',
        'Lead product development and innovation initiatives with a diverse team...',
        '2023-09-10',
        'https://example.com/product-manager-opening',
        90000
    );

**Comment by kahei-li** [comment]
Good work Sana. Don't forget to add some description to what this task is to do with and what's left to be done :)
